### ISSUE TITLE
Update all sources to newer versions

### ISSUE THREAD

**Issue by Potherca** [plantuml/plantuml-stdlib#10]
I've been looking into the various sources used in this repo and there seems to be updates possible.

This is an overview of what needs to be done:

| Source (Repo)                                                                            | Current | Available    |  MR     | Info   |
| ---------------------------------------------------------------------------------------- | ------- | ------------ | ------- | ------ |
| **aws**             <br><sup>`milo-minderbinder/AWS-PlantUML`</sup>                      | 18.2.22 | _Up To Date_ | -       |        |
| **awslib**          <br><sup>`awslabs/aws-icons-for-plantuml`</sup>                      |  7.0.0  | _Up To Date_ | ~~#27~~ | Merged |
| **Azure**           <br><sup>`RicardoNiepel/Azure-PlantUML`</sup>                        |  2.1.0  | _Up To Date_ | -       |        |
| **C4**              <br><sup>`RicardoNiepel/C4-PlantUML`</sup>                           |  1.0.0  | **No info**  | _TODO_  | Version information requested<br><sup>(https://github.com/RicardoNiepel/C4-PlantUML/issues/26)</sup> |
| **cloudinsight**    <br><sup>`rabelenda/cicon-plantuml-sprites`</sup>                    |  1.0.0  | _Up To Date_ | ~~#11~~ | Merged |
| **cloudogu**        <br><sup>`cloudogu/plantuml-cloudogu-sprites`</sup>                  |  1.0.2  | _Up To Date_ | ~~#12~~ | Merged |
| **Elastic**         <br><sup>`Crashedmind/PlantUML-Elastic-icons`</sup>                  |  0.0.1  | _Up To date_ | -       |        |
| **logos**           <br><sup>`rabelenda/gilbarbara-plantuml-sprites`</sup>               |  1.0.0  | _Up To Date_ | ~~#25~~ | Merged |
| **kubernetes**      <br><sup>`michiel/plantuml-kubernetes-sprites`</sup>                 |  5.3.45 | _Up To Date_ | ~~#26~~ | Merged |
| **MaterialDesign**  <br><sup>`Templarian/MaterialDesign`</sup>                           |  0.0.1  | **4.0.96**   | _TODO_  |        |
| **office**          <br><sup>`Roemer/plantuml-office`</sup>                              |  1.0.0  | _Up To Date_ | ~~#14~~ | Merged |
| **osa**             <br><sup>`Crashedmind/PlantUML-opensecurityarchitecture-icons`</sup> |  0.0.1  | _Up To Date_ | -       |        |
| **tupadr3**         <br><sup>`tupadr3/plantuml-icon-font-sprites`</sup>                  |  2.2.0  | _Up To Date_ | ~~#30~~ | Merged |

MRs:

- [x] #11 cloudinsight
- [x] #12 cloudogu
- [x] #14 office
- [x] #30 tupadr3
- [x] #25 logos 
- [x] #26 kubernetes
- [x] #27 awslib

**Comment by arnaudroques** [comment]
Well, it will help if you create a PR about this :-)

**Comment by Potherca** [comment]
I'm hoping to check all libraries for updates and open MRs where needed this coming weekend.

**Comment by Potherca** [comment]
I've opened #13 to update the tupadr3 library. I've also opened an MR to update another lib.

I've made a first stab at automating the update of libs as well: 
 https://gist.github.com/Potherca/d52275853c3fb46e8244616676790b80

I might follow up on that later...

**Comment by Potherca** [comment]
Add MRs to update the INFO fies of  logos #25  and kubernetes #26 to the list.

**Comment by spawn-guy** [comment]
@Potherca is there a "simple" tutorial how to add an icon library?

**Comment by Potherca** [comment]
Not that I know of. As usual, once you _know how_, it isn't all that hard. 

The steps to add an icon library are:

1. Generate PlantUML sprite files
2. Put all of the sprites in a repo
3. Open an MR here to get the sprite repo included into stdLib
   - Including an `INFO` file

## 1. Generate PlantUML sprite files

Generating`.puml` files from a bunch of SVGs can be done using `plantuml.jar -encodesprite`<sup>1</sup>

It is quite common for icon-sets to either exist out of SVGs or be generated from SVGs, so source SVGs are often already available.

Figuring out which settings to use with `encodesprite` can take some trial-and-error.<sup>2</sup> 

I remember looking into https://github.com/tupadr3/font-icon-generator but I can really remember how things work, so for now [YMMV](https://en.wiktionary.org/wiki/your_mileage_may_vary).

## 2. Put all of the sprites in a repo

Once you have a bunch of generated `.puml` files, it is a good idea to create a common/main file that includes all the sprites, to save users the hassle of having to load each sprite individually.<sup>3</sup>

Adding a README explaining things a bit is also a good move.

## 3. Open an MR here to get the sprite repo included into stdLib

To add an icon library to this project (i.e.e the PlantUML stdLib), open a merge request with:<sup>4</sup>

- A folder containing all of your PlantUML sprite files
- An entry to README file
- An `INFO` file
 
### Including an `INFO` file

The `INFO` file should contain the version (i.e. the git tag or github release) of the icon-set you are adding and the source repo.

For instance:

```
VERSION=1.2.0
SOURCE=https://github.com/path-to/project
```

If the _source_ repo tags newer versions when things change, updating things here can be automated.<sup>5</sup>

In the long run, it _could_ even be possible to add/update icon-sets here without an intermediary repo, but for now, this is how it is done.

## Footnotes

1. To quote [the manual entry on sprites](https://plantuml.com/sprite):
   > To encode sprite, you can use the command line like: `java -jar plantuml.jar -encodesprite 16z foo.png` where `foo.png` is the image file you want to use (it will be converted to gray automatically). After `-encodesprite`, you have to specify a format: `4`, `8`, `16`, `4z`, `8z` or `16z`. The number indicates the gray level and the optional `z` is used to enable compression in sprite definition.

2. This [blog post by Hubert Klein Ikkink](https://mrhaki.blogspot.com/2017/10/plantuml-pleasantness-creating-our-own.html) might be of some help

3. Look at existing sprite sets for inspiration

4. A good example of this is [#18](https://github.com/plantuml/plantuml-stdlib/pull/18/files?file-filters%5B%5D=.md&file-filters%5B%5D=No+extension) 

5. That is in fact what I have been doing for all MRs opened for this ticket

**Comment by Potherca** [comment]
Update:

- MR #13 has been superseded by #30 which has been merged, so tupadr3 is now also up-to-date.

**Comment by Potherca** [comment]
The only two items remaining are `RicardoNiepel/C4-PlantUML` which seems to be dead in the water and `Templarian/MaterialDesign` which has moved to https://github.com/Templarian/MaterialDesign-SVG.

As both of these will require separate attention, I am closing this issue.

Any follow-ups can be separate tickets/MRs.

**Comment by Potherca** [comment]
`RicardoNiepel/C4-PlantUML` has been revived and a `v2.0.0` has been tagged!
