### ISSUE TITLE
Integrating latest version of AWS Icons for PlantUML 

### ISSUE THREAD

**Issue by gadams999** [plantuml/plantuml-stdlib#15]
Hi all,

I noticed that the awslabs library is now included in the stdlib. Nice!

 I'm one of the maintainers of the source repository and would be interested in how I can incorporate a pull request when we process the latest version of the icons.

We've just finished the v6.0 version (released on 2020-01-31), and the plan is to release within 30-45 days after the quarterly updates are released directly from AWS Marketing.

Any guidance on the format of a PR would be appreciated!

**Comment by arnaudroques** [comment]
Well, thanks for your work. We've just granted you write access to the stdlib repository.
Do whatever you find usefull. Some advices:

- Keep the INFO file up to date with the corresponding version of AWS icons set
- Stick to .puml files

Tell us if you need more information!

**Comment by Potherca** [comment]
@gadams999 I've already automated the process of updating all sprites (not just the AWS ones) as part of my effort for https://github.com/plantuml/plantuml-stdlib/issues/10

I'm still waiting for the related MRs to be merged, though.

Once they go through it would be super simple (for me anyway) to set up a GitHub Action (either here or in source repos) to make sure things stay up to date.

I've documented the "magic" here: https://gist.github.com/Potherca/d52275853c3fb46e8244616676790b80

Feel free to ping me if you would like more info on automating this...
