### ISSUE TITLE
Question on new preprocessor

### ISSUE THREAD

**Issue by coryodaniel** [plantuml/plantuml-stdlib#21]
I've upgraded to using the new preprocessor and Im experience a "lost of functionality" with converting from !define to !function.

Given these two implementations:

```plantuml
!define OldComponent($alias, $label, $techn) rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[$techn]</size>//" <<component>> as $alias

!unquoted function NewComponent($alias, $label, $techn)
rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[$techn]</size>//" <<component>> as $alias
!endfunction
```

The `OldComponent` would allow adding links to the rectangle, but `NewComponent` silently accepts it, but will not render it.

```plantuml
@startuml Basic Sample
!include lib.puml

OldComponent(foo, "Foo", "foo") [["http://example.com/foo"]]
NewComponent(bar, "Bar", "bar") [["http://example.com/bar"]]

@enduml
```

The image renders fine, but the cmapx renders:

```html
<map id="plantuml_map" name="plantuml_map">
<area shape="rect" id="id1" href="http://example.com/foo" title="http://example.com/foo" alt="" coords="6,8,304,79"/>
</map>
```

Is this functionality thats no longer available or is there a new way to do something similar?

**Comment by arnaudroques** [comment]
As general rules, _!define_ should be changed to _return function_.

So you should have

```
@startuml
!$TECHN_FONT_SIZE = 14
!define OldComponent($alias, $label, $techn) rectangle "==$label\n//<size:$TECHN_FONT_SIZE>[$techn]</size>//" <<component>> as $alias

!unquoted function NewComponent($alias, $label, $techn)
!return 'rectangle "==' + $label + '\n//<size:' + $TECHN_FONT_SIZE + '>[' + $techn + ']</size>//" <<component>> as ' + $alias
!endfunction

OldComponent(foo, "Foo", "foo") [["http://example.com/foo"]]
NewComponent(bar, "Bar", "bar") [["http://example.com/bar"]]
@enduml
```

Which is [rendering this](http://www.plantuml.com/plantuml/svg/XP3HIyCm4CRVyrTSIw4EXq7mQRHbE3RqfNjmJzOoilRg2cbIqmJ5lzuBjKW7wjFbyjtttIzP3rOOwph9M10Tjfk7_BZRvuVZq-Fp5bAulMD1ZKsh4FQotkYkrmgLlOg4RCMmX4YA4qgg5gkpMe31oWhrAX72D1t55yLvChIVkBhCpuhHLYRSwndd8IH9DIt9CX03Z9k8pgatfotMq3XLsLOhoF7zNo8M6BJEA8XdQ35SVq_I8Vv1zFUNc7uYAxmoPlh-JsGQdR03LFN4ozZi2nkjbn3kj0wfD5GMK1JXsTf-nJb-YAwNU4F9t6jboMQlFGb3hdjXl9cQNysaUVEQE5mdlm00).

Hope this helps!
Tell us if you find other issue with converting.

**Comment by coryodaniel** [comment]
Awesome, much appreciated!!!
