### ISSUE TITLE
Update C4

### ISSUE THREAD

**Issue by Potherca** [plantuml/plantuml-stdlib#31]
Pending the outcome of https://github.com/RicardoNiepel/C4-PlantUML/issues/81, once various changes have been integrated and tagged/released, they need to be updated here.

An MR will follow at such a time.

**Comment by arnaudroques** [comment]
Sure, we would be glad to integrate all changes decided by the community.
As you may know, we are focusing on the core PlantUML library itself and we let users organize themselve :-)

Thanks to all ( @RicardoNiepel @adrianvlupu @Potherca @aheil @IOrlandoni @stawirej ) for your work !

**Comment by Potherca** [comment]
@arnaudroques Of-topic for C4, but regarding organising ourselves, there is talk of bringing various libraries/repos that have been added to plantuml-stdlib together under a single GitHub Organisation.

The current idea is to use https://github.com/plantuml-stdlib/

Is it okay if we use that name? Or would you rather we use something else?

**Comment by arnaudroques** [comment]
That's fine !

**Comment by RicardoNiepel** [comment]
@arnaudroques thanks a lot for making this possible!

**Comment by Potherca** [comment]
Closing this as it was resolved by #36.
