### ISSUE TITLE
New Logo for Thymeleaf

### ISSUE THREAD

**Issue by daheile** [plantuml/plantuml-stdlib#41]
Very low priority, no issue at all, but it would be nice to have a sprite/logo for Thymeleaf.

Logo can be found here
https://www.thymeleaf.org/download.html#artwork

**Comment by Potherca** [comment]
I have made a request in the upstream library where a lot of the logos come from: https://github.com/gilbarbara/logos/issues/510

**Comment by Potherca** [comment]
The waiting is now for a response from the Tymeleaf team: https://github.com/thymeleaf/thymeleaf.github.com/issues/41

**Comment by daheile** [comment]
Thanks!
