### ISSUE TITLE
icon logos/firebase is not corret

### ISSUE THREAD

**Issue by swiftech** [plantuml/plantuml-stdlib#44]
https://github.com/plantuml/plantuml-stdlib/blob/master/logos/firebase.puml

<img width="143" alt="Screen Shot 2021-07-30 at 12 24 25 PM" src="https://user-images.githubusercontent.com/3277107/127600049-4ae4df20-6e85-4863-ad87-f62279cac8de.png">

**Comment by Potherca** [comment]
@swiftech Thank you for reporting this! My apologies for my late reply... This whole Pandemic is reaking havoc on the time I have for open-source :disappointed: 

Regarding the issue:

The base  image (from https://raw.githubusercontent.com/gilbarbara/logos/) looks alright: 

<img src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/firebase.svg" width=100/>

It looks like only the first "leaf" of the three in the logo is converted.
This is an problem in https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites.

 I've opened an issue to fix it there (https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites/issues/2)

Once that has been resolved things can be updated here to resolve this issue.

**Comment by Potherca** [comment]
The issue in the source repo has been fixed. I'll open an MR to update things here. :+1:

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @swiftech  for the report.
- Thanks @Potherca  for your work _(That is fixed by: https://github.com/plantuml/plantuml-stdlib/commit/b15285de9868e810c7b018fb7306d206eea8fd9d)_

Regards.
