### ISSUE TITLE
AwsLib breaking change on entity casing? 

### ISSUE THREAD

**Issue by Tyrannoseanus** [plantuml/plantuml-stdlib#47]
The latest change to the awslib icons (https://github.com/plantuml/plantuml-stdlib/commit/82a5108a2b773b6698f5a452d520fa0226f004dc) introduced a breaking change to a few entities- at least [TapeStorage](https://github.com/plantuml/plantuml-stdlib/blob/master/awslib/General/TapeStorage.puml) and [TraditionalServer](https://github.com/plantuml/plantuml-stdlib/blob/master/awslib/General/TraditionalServer.puml), but not in entities such as [RoboMakerSimulation](https://github.com/plantuml/plantuml-stdlib/blob/master/awslib/Robotics/RoboMakerSimulation.puml).

The change is that these entities are now referred to without camel case, so `TraditionalServer` became `Traditionalserver` instead.

Was this change intentional? Is there a reason some entities have been changed but others remain camel cased?

**Comment by arnaudroques** [comment]
@mmajis Any idea about this ?

@SeanOToole We let the community manage the stdlib. If this camel case change is an issue for your, you can submit a PR where both defines (that is `Tapestorage` and `TapeStorage`) are declared.

**Comment by mmajis** [comment]
This change has happened upstream. Previous version was https://github.com/awslabs/aws-icons-for-plantuml/tree/v7.0/dist/General and now we have https://github.com/awslabs/aws-icons-for-plantuml/tree/v10.0/dist/General where indeed `TapeStorage` Has changed to `TapeStorage`, for example.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered.
- Thanks @Tyrannoseanus  for the report.
- Thanks @mmajis  for your answer.
- Thanks PlantUML team for your work.

Regards.
