### ISSUE TITLE
Snowflake Logo

### ISSUE THREAD

**Issue by ghost** [plantuml/plantuml-stdlib#58]
Hey, is there a Snowflake logo available?

**Comment by The-Lum** [comment]
Hello @CeasarJBV, and all,

Here are some possibilities:
- using the `lib` [`tupadr3`](https://github.com/plantuml/plantuml-stdlib/tree/master/tupadr3) _[src.: [`tupadr3`](https://github.com/tupadr3/plantuml-icon-font-sprites)]_:
  - use `WEATHER_SNOWFLAKE_COLD` with [`weather`](https://github.com/tupadr3/plantuml-icon-font-sprites/blob/master/weather/index.md)
  - use `FA5_SNOWFLAKE` with [`FA5 (font-awesome-5)`](https://github.com/tupadr3/plantuml-icon-font-sprites/blob/master/font-awesome-5/index.md)

- Or without `lib`:
  - using `unicode`: `<U+2744>` 
  - using `emoji`: `<:snowflake:>` :snowflake:
  - _or perhaps a lot of other solutions..._

Regards.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now answered _(by me 😆)_ 
- Thanks for the question.

Regards.
