### ISSUE TITLE
In awslib, all.puml does not contains all icons

### ISSUE THREAD

**Issue by arnaudroques** [plantuml/plantuml-stdlib#59]
For example, in https://github.com/plantuml/plantuml-stdlib/blob/master/awslib/EndUserComputing/all.puml there is nothing about https://github.com/plantuml/plantuml-stdlib/blob/master/awslib/EndUserComputing/Appstream2_0.puml

@mmajis Any idea?

Thanks!

**Comment by mmajis** [comment]
It looks like `Appstream2_0.puml` changed to `Appstream.puml` in upstream tag v9.0. The icon is essentially the same: https://github.com/awslabs/aws-icons-for-plantuml/tree/v9.0/dist/EndUserComputing 

https://github.com/plantuml/plantuml-stdlib/blob/master/awslib/EndUserComputing/Appstream2_0.puml is from [v7.0](https://github.com/awslabs/aws-icons-for-plantuml/tree/v7.0/dist/EndUserComputing) that I didn't delete when I updated the icons last year.

There might be other such old files in other directories too. Deleting them would break any existing service-specific includes that reference the old files.

**Comment by arnaudroques** [comment]
Thanks, that's make sense.

For the record, the fixed version of the OP issue is

```
@startuml
!include <awslib/AWSCommon>
!include <awslib/AWSSimplified.puml>
!include <awslib/Compute/all.puml>
!include <awslib/mobile/all.puml>
!include <awslib/general/all.puml>
!include <awslib/GroupIcons/all.puml>
!include <awslib/CustomerEngagement/all.puml>
!include <awslib/NetworkingAndContentDelivery/all.puml>
!include <awslib/EndUserComputing/all.puml>
!include <awslib/ApplicationIntegration/all.puml>


AppStream(AppStream, " ", " ")
AutoScalingGroup(AutoScalingGroup, " ", " ")
EC2Instance(EC2Instance, " ", " ")
Internetalt1(Internetalt1, " ", " ")
DirectConnect(DirectConnect, " ", " ")
VPCVPNConnection(VPCVPNConnection, " ", " ")
VPCSubnetPublic(VPCSubnetPublic, " ", " ")
VPCSubnetPrivate(VPCSubnetPrivate, " ", " ")
VPCInternetGateway(VPCInternetGateway, " ", " ")
VPCCustomerGateway(VPCCustomerGateway, " ", " ")
TransitGateway(S3TransitGatewayStaging, " ", " ")
VPCElasticNetworkInterface(VPCElasticNetworkInterface, " ", " ")
ELBNetworkLoadBalancer(ELBNetworkLoadBalancer, " ", " ")

Cloudalt(Cloudalt, " ", " ")
@enduml
```
