### ISSUE TITLE
Last version of gilbarbara / logos library

### ISSUE THREAD

**Issue by nicolasleborgnelv** [plantuml/plantuml-stdlib#69]
Hello, 
Is it possible to update logo library with last version of gilbarbara/logo library ?
Regards

**Comment by arnaudroques** [comment]
Sure, the easiest way would be that you provide a pull request with last version.
Is is possible for you? Thanks!

**Comment by Potherca** [comment]
I can provide the required MR from the [plantuml-stdlib/gilbarbara-plantuml-sprites](https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites) repo.

The current sprites are from 10 month ago (https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites/commit/37243cd342ba968072ae29440d55a2174f3db38c) so I'll need to run the update script and tag a new version first.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed by:
- #80 

Thanks:
- @nicolasleborgnelv  for the report.
- @Potherca for your work.

Regards.
