### ISSUE TITLE
AzureCommon.puml missing from Azure stdlib?

### ISSUE THREAD

**Issue by ErikNell** [plantuml/plantuml-stdlib#70]
This snippet:
 `@startuml
!include <azure/AzureCommon>

@enduml`

will give error "Cannot include <azure/AzureCommon>"

It looks like  AzureCommon.puml, AzureRaw.puml, AzureSimplified.puml and AzureC4Integration.puml are missing from the stlib.
Not sure if this is intended or an oversight.

**Comment by Potherca** [comment]
That looks like an oversight... Those files _are_ present [in the source](https://github.com/plantuml-stdlib/Azure-PlantUML/tree/master/dist) but it looks like they are _missing_ in the MR https://github.com/plantuml/plantuml-stdlib/commit/db233ddaa00afa6e4fe6ac4a8de01e332b61bca4#diff-060aaf8fa63fc5f09dd0c825e526b4f29ed13996889870a6a55d86a1db63e897

I'll add a fix ASAP.

**Comment by The-Lum** [comment]
FYI `Azure stdlib` was updated last week:
 - #68

Perhaps ask your question to the author/maintainer: @Potherca.

On this PR #68 , we notice the disappearance of:
- azure/AzureC4Integration.puml
- azure/AzureCommon.puml
- azure/AzureRaw.puml
- azure/AzureSimplified.puml

Is it normal or not?

Perhaps as `awslib` it will be necessary to manage different version in parallel... _to manage backward compatibility._
(Similar to #64 and #65)

Thanks for clarification.
Regards.

**Comment by The-Lum** [comment]
Thanks @Potherca for your prompt answer.
Regards.

**Comment by Potherca** [comment]
Looks like I somehow missed the mentioned files _and_ some new icons. :astonished: 

I opend #71 to fix this issue. Apologies for the oversight. 

@ErikNell Thank you very much for reporting this!

**Comment by ErikNell** [comment]
@Potherca : Thanks for the quick reaction.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @ErikNell for the report.
- Thanks @Potherca  for your work.

Then you can close this issue.
Regards.
