### ISSUE TITLE
EIP

### ISSUE THREAD

**Issue by theavege** [plantuml/plantuml-stdlib#88]
Please include to stdlib [EIP](https://github.com/plantuml-stdlib/EIP-PlantUML)

**Comment by arnaudroques** [comment]
It would help if you could propose a PR here with files from https://github.com/plantuml/plantuml-stdlib
Do you know how to do that?
Thanks!

**Comment by theavege** [comment]
Sorry. I don't know how to do that. Do you have instructions?

**Comment by The-Lum** [comment]
Hi @theavege, and all,

>Do you have instructions?

See some elements here:
- [CONTRIBUTING on `plantuml/plantuml-stdlib`](https://github.com/plantuml/plantuml-stdlib/blob/master/CONTRIBUTING.md)

And here's a quick detailed procedure:
1. [Fork `plantuml/plantuml-stdlib`](https://github.com/plantuml/plantuml-stdlib/fork) and then git clone
2. Create a new branch _(the name is full open, no constrains)_ like `new_lib`, `add/EIP` or `update/EIP`, or  `add_EIP` or `update_EIP`
3. Create a new folder `eip` [for the EIP Library] _(preferably on lowercase: only `C4` and `DomainStory` have uppercase!)_ on your branch created on (2)
4. Copy only final folder/files _(not input files [e.g. folder `scripts` or `test` are no needed])_
    - from [`plantuml-stdlib/EIP-PlantUML`](https://github.com/plantuml-stdlib/EIP-PlantUML)
    - to your new folder `eip` of your branch created on (2)-(3)
6. Create an `INFO` file as described on [CONTRIBUTING on `plantuml/plantuml-stdlib`](https://github.com/plantuml/plantuml-stdlib/blob/master/CONTRIBUTING.md)
```
VERSION=1.0.0
SOURCE=https://github.com/plantuml-stdlib/EIP-PlantUML
```
8. Make changes to the `README.md` file to add the EIP Library and describe it.
9. Commit your work and push it up to your fork repository
10. Submit a Pull Request from your fork repository back to the main repository: submit a Pull Request to PlantUML team _([`plantuml/plantuml-stdlib`](https://github.com/plantuml/plantuml-stdlib))_ with your add/update.
11. _Wait Review and PR approval..._

---
Then PlantUML Team and especially @arnaudroques:
1. Accept your PR
2. Transform and Compress the files of the new folder 
3. Make a commit with those files on [`plantuml/plantuml/stdlib`](https://github.com/plantuml/plantuml/tree/master/stdlib)
4. Then your Library will be now packaged on `plantuml.jar`
12. _Enjoy... and share..._ 🎉 

---

See also discussion about EIP Library here:
- #8

_If that can help,_
Regards,
Th.

**Comment by theavege** [comment]
[I did](https://github.com/plantuml/plantuml-stdlib/pull/89)

**Comment by theavege** [comment]
@The-Lum , How to include my theme to [puml-themes](https://github.com/plantuml/puml-themes)?

**Comment by arnaudroques** [comment]
It is [online now](https://www.plantuml.com/plantuml/uml/VP3FIiD04CRlVOfflQJW7yrPf20U10DjnGVOPgVPnVqJPcSF8hwxawnAXJHp29dl-p7ppMuIA-BitM9fG-koHhX7szyyFM-ljau5VcjU7XOWjMI37i4hIcEVtcte5IaFpWRaZnuX4fiucWwF31o1R6SOj2LisSOmUiVeD1AizkfmiDpiLd0nJBZMAXdKy2bGgGPJKXrMFdMtbx_TUig-cxVhAJjrZqQ5WAvgZOotOPSndmDaGSmyHzIJHDcw5mUf8fOzvRyWN-Ft5OF-kL6IhF-qaeluH2eZXeCdjFf4AsyYkVzhzQ09jv4-U_SD) :-)

**Comment by The-Lum** [comment]
Hello @theavege,

Now that the plantuml version contains the EIP library, here are some end actions of documentation...

## On [`plantuml/plantuml-stdlib/README.md`](https://github.com/plantuml/plantuml-stdlib/blob/master/README.md)
- Could you replace on the image source:
  - the currently `!include https://raw.githubusercontent.com/plantuml-stdlib/EIP-PlantUML/main/dist/EIP-PlantUML.puml`
  - by `!include <eip/EIP-PlantUML>`

## On [`plantuml.com/stdlib`](https://plantuml.com/stdlib)
_Through [`alphadoc/stdlib`](http://alphadoc.plantuml.com/doc/markdown/en/stdlib)_
- Could you add documentation about EIP or copy doc. from the above item?

_Thanks a lot._
Regards,
Th.
